server: 
  port: 80
  servlet: 
    context-path: /YiMo

spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5     
# 添加热部署 自动编译       
  devtools: 
    restart: 
      enabled: true  
      additional-paths: src/main/java 
  
  #数据源配置    
  datasource:
    url: jdbc:mysql://localhost:3306/YiMo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver     #驱动
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    
#MyBatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: top.yimo
    configuration:
      mapUnderscoreToCamelCase: true #开启驼峰命名自动转换
      interceptions: top.yimo.common.interceptor.PageInterceptor #配置自定义myBatis拦截器
 
 #日志配置
logging:
  level:
    root: info
    top.yimo: debug