server: 
  port: 80
  servlet: 
    context-path: /YiMo
spring:
  profiles:
    active: dev #使用开发环境配置
  #数据源配置    
  datasource:
    driverClassName: com.mysql.jdbc.Driver     #驱动
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf配置
  thymeleaf:
    check-template-location: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet: 
      content-type: text/html
    mode: HTML  
  #quartz配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: YiMoScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc    
    
#MyBatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: top.yimo
    configuration:
      mapUnderscoreToCamelCase: true #开启驼峰命名自动转换
      cache-enabled: true  #开启二级缓存
      interceptions: top.yimo.common.interceptor.PageInterceptor #配置自定义myBatis拦截器
 
 #日志配置
logging:
  config: classpath:config/logback-spring.xml
  path: /log
  level: 
    root: info
    top.yimo: debug
    
#actuator端口 
#management: 
#  server: 
#    port: 9001
#  endpoints:    
#    web:  
#      base-path:  /actuator #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#  endpoint: #显示健康具体信息  默认不会显示详细信息  
#    health:
#     show-details: always
     
shiro: 
  session:
    timeout: 1800  #单位为秒  默认30分钟
    interval:  600 #检查session有效性频率 默认10分钟一次
  filter: 
    loginurl: /login 
    sucessurl: /index
    unauthorizedurl: /error/403
    
xss: 
  enabled: true #xss过滤开关
  excludes: /favicon.ico,/img/*,/js/*,/css/*  # 不需要过滤的路径（多个用逗号分隔）
  urlPatterns: /*   #需要过滤的路径