spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        url: jdbc:mysql://localhost:3306/YiMo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
        username: root
        password: 
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,log4j
        logSlowSql: true
   # 添加热部署 自动编译       
    devtools: 
        restart: 
            enabled: true  
            additional-paths: src/main/java 
   #thymeleaf配置
    thymeleaf:
        cache: false #开发环境 关闭缓存   

#MyBatis配置
mybatis:
      configuration:
        cache-enabled: false  #开发环境  关闭缓存
    