spring:
  #数据源配置    
  datasource:
    druid: 
        url: jdbc:mysql://localhost:3306/YiMo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
        username: root
        password: 

 #thymeleaf配置
  thymeleaf:
    cache: false #开发环境 关闭缓存   
    #MyBatis配置
mybatis:
      configuration:
        cache-enabled: false  #开发环境  关闭缓存
 #日志配置
logging:
  path: /log
  level: 
    top.yimo: debug
yimo: 
  permissions: false  #开发环境关闭权限认证 方便调试接口
  kickout:         #开发环境关闭在线用户数控制
    kickout : true
    isAfter: false  #是否踢出后来登录的，默认是false；即后者登录的用户踢出前者登录的用户
    maxSession: 1  #允许同时在线个数
  logModel: file  #操作日志输入到db或者file