yimo:
  downloadPath: d:/
  uploadPath: upload/
  isDemo: false
  refusedURI: batchRemove@remove@save@update
  loginHtml: login_1
server: 
  port: 80
  servlet: 
    context-path: /YiMo
spring:
  profiles:
    active: dev #使用开发环境配置
  #数据源配置    
  datasource:
    driverClassName: com.mysql.jdbc.Driver     #驱动
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf配置
  thymeleaf:
    check-template-location: true
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet: 
      content-type: text/html
    mode: HTML  
  #quartz配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: YiMoScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc    
    
#MyBatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    typeAliasesPackage: top.yimo
    configuration:
      mapUnderscoreToCamelCase: true #开启驼峰命名自动转换
      cache-enabled: true  #开启二级缓存
 
 #日志配置
logging:
  config: classpath:config/logback-spring.xml
  path: /log
  level: 
    root: info
    top.yimo: info
    
 #pageHelper配置   
pagehelper:
    helperDialect: mysql
    reasonable: true  #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
    supportMethodsArguments: true
    params: count=countSql
     
shiro: 
  session:
    timeout: 1800  #单位为秒  默认30分钟
    interval:  600 #检查session有效性频率 默认10分钟一次
  filter: 
    loginurl: /login
    sucessurl: /index
    unauthorizedurl: /error/403
    
xss: 
  enabled: true #xss过滤开关
  excludes: /favicon.ico,/img/*,/js/*,/css/*  # 不需要过滤的路径（多个用逗号分隔）
  urlPatterns: /*   #需要过滤的路径
  
  
#blog相关配置
blog: 
    articlePageSize: 6 #每页文章数量
    commentPgaeSize: 6 #每页评论数量
    pageMax: 20 #最大页数 
    weibo: 
    zhihu: 
    github: 
    twitter: 
    hitExceed: 1 #点击更新次数 默认设置点击1次就更新 
    hitsLimitTime: 7200  #默认2小时7200秒 内同一个ip点击算一次
    commentLimitTime: 5 #默认5秒内只允许评论一次