spring:
  #数据源配置    
  datasource:
    druid: 
        url: jdbc:mysql://localhost:3306/YiMo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=UTC
        username: root
        password: 
   #热部署配置     
  devtools: 
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #设置重启的目录
      additional-exclude: src/main/resources  #配置内容修改不重启
 #thymeleaf配置
  thymeleaf:
    cache: false #开发环境 关闭缓存   
    #MyBatis配置
mybatis:
      configuration:
        cache-enabled: false  #开发环境  关闭缓存
 #日志配置
logging:
  path: /log
  level: 
    cn.tayle: debug
yimo: 
  permissions: true  #开发环境关闭权限认证 方便调试接口 关闭会同时使kick拦截器失效
  kickout:       
    isAfter: false  #是否踢出后来登录的，默认是false；即后者登录的用户踢出前者登录的用户
    maxSession: 1  #允许同时在线个数
  logModel: file  #操作日志输入到db或者file
  
